services:
  servicepro:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      BACKUP_DIR: /app/backups
    volumes:
      - ${NAS_BACKUP_DIR:-./backups}:/app/backups
    restart: unless-stopped
